/**
 * Additional environment bindings that are authored locally instead of generated by Wrangler.
 */
interface Env {
	TURNSTILE_SECRET_KEY?: string;
	TURNSTILE_SITE_KEY?: string;
	IMPORT_TOKEN?: string;
}
